# Introduction 
## Overview of the NAP Process

The National Adaptation Plan (NAP) process was established under the United Nations Framework Convention on Climate Change (UNFCCC) in 2010 as part of the Cancun Adaptation Framework. The process enables Parties to the UNFCCC to formulate and implement NAPs as a means of identifying medium- and long-term adaptation needs and for developing and implementing strategies and programs to address those needs. The NAP should be understood as a continuous, progressive, and iterative process that follows a country-driven, gender-responsive, participatory, and fully transparent approach. The objectives of the NAP process are :
* 	To reduce vulnerability to the impacts of climate change by building adaptive capacity and resilience; and 
* 	To facilitate the integration of climate change adaptation, in a coherent manner, into relevant new and existing policies, programs and activities, in particular development planning processes and strategies, within all relevant sectors and at different levels, as appropriate.

In practical terms, these objectives cover not only specific projects and programs aimed at decreasing vulnerability, but also a broader evolution of governance so that climate change considerations are mainstreamed into governance processes.  

## NAP Vision 

Sierra Leone reduces vulnerability by half by 2030 through increased risk awareness, improvements in rule compliance, increased institutional capacity and an integrated gender-responsive approach to adaptation in development policy and programs across sectors and scales. 

## NAP Mandate 

The mandate for Sierra Leone’s NAP is grounded in its National Climate Change Strategy and Action Plan and its latest Medium-Term National Development Plan (2019-2023) which includes a cluster on addressing vulnerabilities and building resilience. The NAP builds on these existing policies and supports their implementation. Additionally, the NAP is aligned with the National Climate Change Policy Framework (2012), Nationally Determined Contribution (NDC), National Communications to the UNFCCC and National Adaptation Programmes of Action (NAPA). The NAP process supports the implementation of these policies and the forthcoming updated NDC.

## NAP Process in Sierra Leone

The Government of Sierra Leone (GoSL)  views its NAP as a continuous, progressive and iterative process to ensure a systematic and strategic approach to climate change adaptation in all government decision making, which will facilitate institutional coordination, resource mobilization, technology transfer and—ultimately—effective adaptation actions (Government of Sierra Leone 2019).

The Government of Sierra Leone officially launched its NAP process in 2018. Representatives of the GoSL attended the training workshop on NAP formulation organized by the UNFCCC Least Developed Countries Expert Group (LEG) in Nairobi. Following this, the country developed a NAP Framework in January 2019 and a Climate Change Communications Strategy under the National Adaptation Plan in 2020. This initial NAP continues the process of developing the institutional framework for medium- and long-term adaptation planning. In summer 2020, the two lead organizations, the SL-EPA and SL-MET convened several meetings to discuss the NAP, its process and priorities. 

In October 2020, an inception workshop with representatives from the national and subnational government, private sector and civil society across all identified priorities was held. This workshop raised awareness about the NAP process, engaged key stakeholders in the planning and decision-making process and collected relevant data to inform the initial NAP. During the workshop, stakeholders discussed all the key elements that are integrated into this document. This convening, along with subsequent consultations, and a policy and literature review has informed the development of the NAP as a collaborative planning process. The draft NAP was shared with internal and external stakeholders for comment, inputs and feedback. Following this review and revision, a validation workshop was held in April 2021 to finalize the NAP and integrate further comments. A list of all those consulted throughout this process and the organizations that reviewed the document are included in Annex 1.  

The NAP process helps Sierra Leone to further identify and address key adaptation issues, gaps, priorities and resource requirements for more effective planning, implementation and monitoring of adaptation in support of the NDCs and the Paris Agreement.  Sierra Leone recognizes that establishing synergies and linkages, where possible, between the NAP and those other key processes is essential to:  

* 	Contributing to achieving the Global Goal on adaptation by reducing vulnerability through integrating adaptation considerations into all relevant plans, policies, and strategies, and prioritizing and plan for adaptation   
* 	Ensuring that the adaptation component of the NDCs becomes a strategic and ambitious vehicle for capturing, reporting and updating commitments and progress
* 	Aligning long-term national development priorities with the SDG framework.

Through the process to develop this NAP, five priority sectors and two cross-cutting priorities were identified. These priorities are the central pillars that are used to guide the document and are directly connected to the Medium-Term Development Plan (2019-2023). The sectors are:

1.	Agriculture and Food Security
2.	Water Resources and Energy
3.	Coastal Zone Management (including fisheries, coastal ecosystems etc.),
4.	Environment (including tourism, land, mineral resources, forestry, etc.)
5.	Disaster management 
6.	Cross-cutting priority 1: Gender Equality and Social Inclusion (focusing on youth, women, elderly, persons with disabilities)
7.	Cross-cutting priority 2: Hard and Soft Infrastructure (including health, water and sanitation, transportation etc.)

## Functions 

The NAP includes a stock take of adaptation priorities, vulnerabilities, and measures across identified priority sectors.

The functions of this are to:
* 	Support the development of vulnerability assessments that inform new policies, projects and programs and guide monitoring and learning
* 	Effectively communicate adaptation priorities and ambitions for the country
* 	Guide investments in climate change adaptation for the short and long-term
* 	Provide a guidance for stakeholder engagement and strategic partnerships for climate change adaptation across sectors
* 	Identify entry points for information gathering, analysis, and dissemination
* 	Serve as a basis for resource mobilization
* 	Support mainstreaming of gender equality and social inclusion 

## Guiding Principles

The guiding principles of the NAP are: 

*	Inclusivity (ownership and shared responsibility) - The NAP Process will be inclusive in its process and implementation and consider the needs of all 	stakeholders in order to foster collaboration, coordination and networking among all stakeholders involved in the NAP process and climate change adaptation initiatives.
*	Participation - The  NAP development and implementation will include participation of state and non-state stakeholders including vulnerable groups.
*	Data generation - The NAP process will be part of a data collection effort to be able to incorporate the best available information into planning
*	 Transparency - The  NAP development and implementation will be open to the public and make its decision-making processes open. 
*	Accountability - The process of developing and implementing the NAP will be guided by an open and transparent manner and guided by systems that allow the continual assessment of practice and performance.
*	Learning/reflexivity- The NAP will build capacity for reflecting on national adaptation actions to foster engagement in a process of continuous policy and community learning (from experience). 
*	Adaptability – This NAP should be seen as the first step in a continuous process of planning, implementation, monitoring and evaluation. It should be revised in consultation with all stakeholders as new climate, vulnerability and socioeconomic information, implementation lessons and best practices are available. 	 		
*	Religious and cultural leadership- The NAP will support activities that build climate-relevant religious and cultural knowledge to leverage the positive influences of religion and culture on the role local leaders play in achieving climate change adaptation outcomes at the local level.

*	Ethical citizenship- NAP implementation is likely to be improved with increased public awareness and citizen buy-in in the context of how individuals conceive their rights and responsibilities and the implications of their assumptions in a changing climate. 

*	Integrate Gender Equality and Social Inclusion in the objectives of the NAP and in its prioritized actions - The NAP will promote an inclusive environment by ensuring institutions promote gender equality and equality of opportunity for women, children, and persons with disability.

*	Capacity development- Achieving NAP goals will require strengthening human, financial, and technical capacities amongst all relevant stakeholders and institutions. 

## Goals

The NAP goals are the following: 

*	Increase resilience capacity at all scales 
*	Support an integrative approach to climate change adaptation programming and policymaking
*	Allocate 10% of annual national budgets to climate change adaptation across sectors
*	Harmonize climate-relevant policies and regulations to improve coordination and cross-sector linkages
*	All local councils have adaptation mainstreamed into local development plans by 2025
*	Institutionalize NAP implementation through laws, policies, and regulations
*	Establish a National Trust Fund for channeling adaptation support across sectors
*	Direct 40% of international development funding toward adaptation priorities across different sectors

## Overview of the NAP

The plan includes eight chapters. Chapter 2 describes the national circumstances in Sierra Leone to provide a background to understand how climate risks interact with the existing development context. Chapter 3 provides the climate science basis to inform adaptation planning in Sierra Leone including impacts and vulnerabilities on priority sectors. Chapter 4 presents the existing climate policy landscape and policies and plans that are related to the NAP. Chapter 5 analyzes existing adaptation priorities in Sierra Leone’s current policies. Chapter 6 provides the institutional arrangements for the NAP including the links between the NAP and the Medium-Term Development Plan, the process to integrate adaptation into development planning and the proposed coordination mechanisms. Chapter 7 presents the next steps in the NAP process including a timeline and implementation strategy
