# Next Steps

## Introduction 

This chapter presents the next steps in the NAP process. This includes a roadmap with key activities and an implementation plan. These next steps are part of an iterative process which will lead to subsequent versions of a NAP and its implementation. 

## NAP Process Roadmap

__2021__  

*	Validation of initial NAP 
*	Submission of initial NAP to UNFCCC
*	Validation of National Framework for Climate Services (to inform full NAP and NDC review)
*	Two NSC meetings to plan for the NAP process
*	Formalized steering and interagency coordination groups 
*	Regional consultations on NAP and NDC review process
*	Finalization of National Electrification Plan (to inform NAP and NDC review)
*	Finalization of NDC review (NAP to inform review)
*	Validation of revised NDC
*	Review of National Climate Change Adaptation Plan 
*	Review of National Climate Change Adaptation Policy
*	Conduct a gender analysis 
*	Consultations on GCF NAP Readiness Grant 
*	GCF NAP Readiness application submitted 
*	Work on integrating climate change into the education curriculum (2021-2022)

__2022__  

*	Award of GCF grant (Q2) (18-24 months implementation)
*	Vulnerability and Risk Assessments
*	Institutional and human capacity needs assessment and strengthening plan
*	Stakeholder consultations 


__2023__  

*	Development of Medium-Term National Development Plan (2024-2029) (NAP process to inform PRSP5)
*	Preparation of full NAP (NAP to be informed by Medium-Term National Development Plan)
*	Validation of NAP

__2024-2029__   

*	NAP priority program Implementation begins
*	4th National Communications (NAP data to inform NC4)
*	Beginning of PRSP5/Medium Term National Development Plan (2024-2029) 
*	Integration of adaptation into national, sector and local planning and budgeting (2025)

## Implementation Strategy: Actions and Needs 

The realization of the actions identified in the NAP will require substantial financial resources, investment, technology development and transfer, and capacity building. International cooperation is an important and necessary prerequisite for leveraging of inputs for the implementation of the NAP.  

__Capacity Development__  

Various institutions and communities involved in the NAP process have considerable technical and non-technical skills that are essential for the NAP process. These capacities, which are found across society including within specialized Ministries, Departments and Agencies (MDAs), state corporations, private sector, research and learning institutions will be utilized in the planning and implementation of the NAP. There are, however, gaps in capacity development and need for further learning and support. These are detailed in the previous chapters. There is a need for support for cooperation across the government and internationally including south-south cooperation, regional cooperation, bilateral and multilateral cooperation. Additional effort will be focused on implementation of a climate curriculum, technical training programs and building south-south exchange and learning programs.  

__Mobilization of Finance__

The priorities included in this document provide various potential projects for public and private and international and national funding. While the costs for this plan cannot be calculated at this stage, there are a few documents that provide an estimate for the costs. The NDC expenditure commitment estimates USD900 Million with most of the financing needed for adaptation. There are also estimates for costs in the MTDP (2019-2023). The total costs for all the priorities that are linked between the NAP and MTDP is approximately $3 billion for the five-year period. The section entitled, “Addressing vulnerabilities and building resilience” includes $96.38 million in costs for five years. Further analysis will need to be conducted for a more accurate accounting.   
Two financing goals have been set out for the NAP:  

1.	Establish a National Trust Fund for channeling adaptation support across sectors
2.	Direct 40% of international development funding toward adaptation priorities across different sectors	  

__Stakeholder Involvement__

Subsequent planning and implementation of the NAP will continue to adopt a collaborative and adaptive learning approach through incorporating inputs from consultative groups and ensure strong involvement of all stakeholders including government agencies, NGOs, private sector, universities, community- based organization, women’s rights organizations. and development partners.   

__Communication Strategy__  

A Climate Change Communications Strategy Under the NAP has been developed. This includes detailed information on targeted messages and is an essential component of the next steps for developing and implementing the NAP. 

__Monitoring and Evaluation, Learning and Reporting__ 

A framework for monitoring and evaluation needs to be developed to support learning, accountability, transparency and reporting. This system needs to be integrated between local and national governments. Given, that the NAP is a working document, there needs to be a system in place to integrate lessons over time. Additionally, there also needs to be a platform created for knowledge sharing and information exchange. This second part requires the development of a data sharing policy which will ensure data exchange between sectors, and between public and private institutions. 
